### ISSUE TITLE
osa03-27_sananelio, palautus ei onnistu

### ISSUE THREAD

**Issue by hannukulmala** [rage/ohjelmointi-22#10]
Tehtävän palautus ei onnistu vaan valittaa mahdollisesta loputtomasta silmukasta, vaikka koodi toimii paikallisesti ja tulostaa oikeat merkkijonot. Sama ongelma niin TMC-pluginin kautta kuin nettisivujenkin kautta palauttaessa.

**Comment by valtlai** [comment]
TMC:n Stderr-välilehdellä näyttää tältä:

```
.F.
======================================================================
FAIL: test_funktio_olemassa (test.test_sananelio.RisunelioTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/test/test_sananelio.py", line 28, in test_funktio_olemassa
    self.module.nelio("", 0)
ZeroDivisionError: integer division or modulo by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/test/test_sananelio.py", line 30, in test_funktio_olemassa
    self.assertTrue(False, f'koodistasi pitäisi löytyä funktio nimeltään nelio')
AssertionError: False is not true : koodistasi pitäisi löytyä funktio nimeltään nelio

----------------------------------------------------------------------
Ran 3 tests in 0.022s

FAILED (failures=1)
```

Saan siis seuraavan virheilmoituksen, vaikka koodini alkaa `def nelio(sana, koko):` eli funktio on kyllä määritetty:

```
FAIL: PythonEditorTest: test_funktio_olemassa
koodistasi pitäisi löytyä funktio nimeltään nelio
```

**Comment by jussmaki** [comment]
Korjattu. Kiitos! :)
